[UI]
options = ["is_construction_term", "is_entity_name", "is_typo", "is_tokenization_error"]
display_range = 15
[Save]
save_dir = "save"
save_file_name = "save.csv"
backup_file_name = "backup.csv"
[Input]
tokens_cols = ["token", "translation"]
filter_na_cols = ["is_construction_term", "is_tokenization_error"]
